# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo-Siri' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Demo-Siri
  pod 'PTDebugView'
end

target 'GXSiri' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GXSiri
#  pod 'PTDebugView'
end

target 'GXSiriUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GXSiriUI
  
end
