# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_SQLite.Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GGXSwiftExtension'
  
  pod 'SQLite.swift'
  # Pods for Demo_SQLite.Swift

end
