# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_AVPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo_AVPlayer
pod 'KJCategories'
  target 'Demo_AVPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo_AVPlayerUITests' do
    # Pods for testing
  end

end
