# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_SDloadImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'SDWebImage'
  # Pods for Demo_SDloadImage

  target 'Demo_SDloadImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo_SDloadImageUITests' do
    # Pods for testing
  end

end
